<script lang="ts">
  import { onMount } from 'svelte';
  import { appState } from './lib/state/appState.svelte';
  import Header from './lib/components/Header.svelte';
  import SplitPane from './lib/components/SplitPane.svelte';
  import ParameterPane from './lib/components/parameters/ParameterPane.svelte';
  import ScenarioSummaryView from './lib/components/analytics/ScenarioSummaryView.svelte';
  import ComparisonView from './lib/components/analytics/ComparisonView.svelte';

  let isLibraryOpen = $state(false);
  let isExportOpen = $state(false);
  let isImportOpen = $state(false);

  onMount(async () => {
    await appState.init();
  });
</script>

<div class="min-h-screen flex flex-col bg-[#09090b] text-zinc-100 font-sans selection:bg-emerald-500/30 selection:text-emerald-200">
  <Header
    onOpenLibrary={() => isLibraryOpen = true}
    onOpenExport={() => isExportOpen = true}
    onOpenImport={() => isImportOpen = true}
  />

  <SplitPane>
    {#snippet left()}
      <ParameterPane />
    {/snippet}

    {#snippet right()}
      <div class="space-y-6">
        <!-- View Switcher / Title Banner -->
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-zinc-800/60 pb-4">
          <div>
            <div class="flex items-center gap-2">
              <span class="text-xs font-mono px-2 py-0.5 rounded font-semibold bg-emerald-950/80 text-emerald-300 border border-emerald-800/60">
                Slot {appState.activeSlotId}
              </span>
              <h1 class="text-xl font-bold text-white tracking-tight">
                {appState.activeSlot.purchase.name}
              </h1>
            </div>
            <p class="text-xs text-zinc-400 mt-1">Real-time simulation generated by Rust WebAssembly engine</p>
          </div>

          <!-- Quick view selector on canvas -->
          <div class="flex items-center gap-1.5 bg-zinc-900/90 p-1 rounded-xl border border-zinc-800/80 text-xs">
            <button
              class="px-3 py-1 rounded-lg transition-all {appState.activeView === 'overview' ? 'bg-zinc-800 text-white font-medium shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => appState.activeView = 'overview'}
            >
              Dashboard
            </button>
            <button
              class="px-3 py-1 rounded-lg transition-all {appState.activeView === 'charts' ? 'bg-zinc-800 text-white font-medium shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => appState.activeView = 'charts'}
            >
              Charts
            </button>
            <button
              class="px-3 py-1 rounded-lg transition-all {appState.activeView === 'statements' ? 'bg-zinc-800 text-white font-medium shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => appState.activeView = 'statements'}
            >
              Statements
            </button>
            <button
              class="px-3 py-1 rounded-lg transition-all {appState.activeView === 'comparison' ? 'bg-indigo-950 text-indigo-200 border border-indigo-700/50 font-medium' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => {
                appState.activeView = 'comparison';
                appState.isComparisonMode = true;
              }}
            >
              Comparison
            </button>
          </div>
        </div>

        <!-- Render Current Active View -->
        {#if appState.activeView === 'overview'}
          <ScenarioSummaryView />
        {:else if appState.activeView === 'comparison'}
          <ComparisonView />
        {:else}
          <ScenarioSummaryView />
        {/if}
      </div>
    {/snippet}
  </SplitPane>
</div>
