<script lang="ts">
  import { onMount } from 'svelte';
  import { appState } from './lib/state/appState.svelte';
  import Header from './lib/components/Header.svelte';
  import SplitPane from './lib/components/SplitPane.svelte';
  import ParameterPane from './lib/components/parameters/ParameterPane.svelte';
  import ScenarioSummaryView from './lib/components/analytics/ScenarioSummaryView.svelte';
  import AnalyticsWorkspace from './lib/components/charts/AnalyticsWorkspace.svelte';
  import StatementWorkspace from './lib/components/statements/StatementWorkspace.svelte';
  import ComparisonView from './lib/components/analytics/ComparisonView.svelte';
  import ScenarioLibraryModal from './lib/components/modals/ScenarioLibraryModal.svelte';
  import ExportModal from './lib/components/modals/ExportModal.svelte';
  import ImportModal from './lib/components/modals/ImportModal.svelte';

  let isLibraryOpen = $state(false);
  let isExportOpen = $state(false);
  let isImportOpen = $state(false);

  onMount(async () => {
    await appState.init();
  });
</script>

<div class="min-h-screen md:h-screen w-full flex flex-col bg-[#09090b] text-zinc-100 font-sans selection:bg-emerald-500/30 selection:text-emerald-200 md:overflow-hidden">
  <Header
    onOpenLibrary={() => isLibraryOpen = true}
    onOpenExport={() => isExportOpen = true}
    onOpenImport={() => isImportOpen = true}
  />

  <SplitPane>
    {#snippet left()}
      <ParameterPane />
    {/snippet}

    {#snippet right()}
      <div class="w-full space-y-6">
        <!-- View Switcher / Title Banner -->
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-zinc-800/60 pb-4">
          <div class="min-w-0">
            <div class="flex items-center gap-2">
              <span class="text-xs font-mono px-2 py-0.5 rounded font-semibold bg-emerald-950/80 text-emerald-300 border border-emerald-800/60 shrink-0">
                Slot {appState.activeSlotId}
              </span>
              <h1 class="text-lg sm:text-xl font-bold text-white tracking-tight truncate">
                {appState.activeSlot.purchase.name}
              </h1>
            </div>
            <p class="text-xs text-zinc-400 mt-1">Real-time simulation generated by Rust WebAssembly engine</p>
          </div>

          <!-- Quick view selector on canvas -->
          <div class="flex items-center gap-1 sm:gap-1.5 bg-zinc-900/90 p-1 rounded-xl border border-zinc-800/80 text-xs overflow-x-auto max-w-full custom-scrollbar shrink-0">
            <button
              class="px-2.5 sm:px-3 py-1.5 rounded-lg transition-all whitespace-nowrap shrink-0 {appState.activeView === 'overview' ? 'bg-zinc-800 text-white font-medium shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => appState.activeView = 'overview'}
            >
              Dashboard
            </button>
            <button
              class="px-2.5 sm:px-3 py-1.5 rounded-lg transition-all whitespace-nowrap shrink-0 {appState.activeView === 'charts' ? 'bg-zinc-800 text-white font-medium shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => appState.activeView = 'charts'}
            >
              Charts
            </button>
            <button
              class="px-2.5 sm:px-3 py-1.5 rounded-lg transition-all whitespace-nowrap shrink-0 {appState.activeView === 'statements' ? 'bg-zinc-800 text-white font-medium shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => appState.activeView = 'statements'}
            >
              Statements
            </button>
            <button
              class="px-2.5 sm:px-3 py-1.5 rounded-lg transition-all whitespace-nowrap shrink-0 {appState.activeView === 'comparison' ? 'bg-zinc-800 text-white font-medium shadow-sm' : 'text-zinc-400 hover:text-zinc-200'}"
              onclick={() => {
                appState.activeView = 'comparison';
                appState.isComparisonMode = true;
              }}
            >
              Compare
            </button>
          </div>
        </div>

        <!-- Render Current Active View with right-canvas freeze guard -->
        <div class={appState.activeSlot.error ? 'opacity-40 pointer-events-none select-none transition-opacity duration-300' : 'transition-opacity duration-300'}>
          {#if appState.activeView === 'overview'}
            <ScenarioSummaryView />
          {:else if appState.activeView === 'charts'}
            <AnalyticsWorkspace />
          {:else if appState.activeView === 'statements'}
            <StatementWorkspace />
          {:else if appState.activeView === 'comparison'}
            <ComparisonView />
          {/if}
        </div>
      </div>
    {/snippet}
  </SplitPane>

  <!-- Modals -->
  {#if isLibraryOpen}
    <ScenarioLibraryModal
      onClose={() => isLibraryOpen = false}
      onOpenImport={() => { isLibraryOpen = false; isImportOpen = true; }}
    />
  {/if}

  {#if isExportOpen}
    <ExportModal onClose={() => isExportOpen = false} />
  {/if}

  {#if isImportOpen}
    <ImportModal onClose={() => isImportOpen = false} />
  {/if}
</div>
