<script lang="ts">
  import { onMount } from 'svelte';
  import { appState } from './lib/state/appState.svelte';
  import Header from './lib/components/Header.svelte';
  import SplitPane from './lib/components/SplitPane.svelte';

  let isLibraryOpen = $state(false);
  let isExportOpen = $state(false);
  let isImportOpen = $state(false);

  onMount(async () => {
    await appState.init();
  });
</script>

<div class="min-h-screen flex flex-col bg-[#09090b] text-zinc-100 font-sans selection:bg-emerald-500/30 selection:text-emerald-200">
  <Header
    onOpenLibrary={() => isLibraryOpen = true}
    onOpenExport={() => isExportOpen = true}
    onOpenImport={() => isImportOpen = true}
  />

  <SplitPane>
    {#snippet left()}
      <div class="p-4 lg:p-6 space-y-6">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <span class="text-sm font-semibold text-zinc-200">⚙️ Parameters</span>
            <span class="text-xs font-mono px-2 py-0.5 rounded bg-zinc-900 border border-zinc-800 text-zinc-400">
              {appState.activeSlot.name}
            </span>
          </div>
        </div>

        <div class="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/40 text-xs text-zinc-400">
          Parameter suite will render here.
        </div>
      </div>
    {/snippet}

    {#snippet right()}
      <div class="space-y-6">
        <div class="flex items-center justify-between border-b border-zinc-800/60 pb-4">
          <div>
            <h1 class="text-xl font-bold text-white flex items-center gap-2.5">
              <span>{appState.activeSlot.purchase.name}</span>
            </h1>
            <p class="text-xs text-zinc-400 mt-1">Real-time simulation generated by Rust WebAssembly</p>
          </div>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div class="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/50 backdrop-blur-sm">
            <span class="text-xs font-medium text-zinc-400">Purchase Price</span>
            <p class="text-xl font-bold font-mono text-white mt-1 tabular-nums">
              ${appState.activeSlot.purchase.house.purchase_price.toLocaleString()}
            </p>
          </div>
          <div class="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/50 backdrop-blur-sm">
            <span class="text-xs font-medium text-zinc-400">Total Borrowed</span>
            <p class="text-xl font-bold font-mono text-zinc-200 mt-1 tabular-nums">
              ${(appState.activeSlot.scenario?.total_statement.total_paid ? (appState.activeSlot.purchase.house.purchase_price - (appState.activeSlot.purchase.tools.find(t => 'Cash' in t)?.Cash?.amount || 0)).toLocaleString() : '0')}
            </p>
          </div>
          <div class="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/50 backdrop-blur-sm">
            <span class="text-xs font-medium text-zinc-400">Total Interest Paid</span>
            <p class="text-xl font-bold font-mono text-rose-400 mt-1 tabular-nums">
              ${(appState.activeSlot.scenario?.total_statement.total_interest_paid.toLocaleString(undefined, { maximumFractionDigits: 0 }) || '0')}
            </p>
          </div>
          <div class="p-4 rounded-xl border border-zinc-800/80 bg-zinc-900/50 backdrop-blur-sm">
            <span class="text-xs font-medium text-zinc-400">Tax Savings Realized</span>
            <p class="text-xl font-bold font-mono text-emerald-400 mt-1 tabular-nums">
              ${(appState.activeSlot.scenario?.total_statement.total_tax_savings.toLocaleString(undefined, { maximumFractionDigits: 0 }) || '0')}
            </p>
          </div>
        </div>
      </div>
    {/snippet}
  </SplitPane>
</div>
